class ReportModel {
  final String? id,
      familyHistory,
      specifyFamilyHistory,
      specifyPersonalHistory,
      previousDiabetes,
      diabetesComplications,
      previousHTN,
      specifyAllergy,
      allergyTreatment,
      specifySurgery,
      menarche,
      ageFirstIntercourse,
      numberOfIVGs,
      breastfeeding,
      numberOfPregnancies,
      numberOfParity,
      numberOfChildren,
      numberOfMiscarriages,
      firstPregnancyAge,
      specifyPregnancy,
      contraception,
      hormonalContraception,
      gynecologicalActivity,
      menopause,
      packYear,
      specifyDrugUse,
      otherHabits,
      history,
      initialDiagnosis,
      total,
      doctorName,
      doctorSpecialty,
      patientId;
  bool? noFamilyHistory,
      personalCancerHistory,
      noMedicalHistory,
      hasDiabetes,
      hasHTN,
      hasCoronaryDisease,
      hasCardiacDisease,
      hasRenalDisease,
      hasLiverDisease,
      hasChronicRespiratoryDisease,
      hasAllergy,
      noSurgicalHistory,
      hasSurgery,
      noObstetricGynecHistory,
      isPregnant,
      noHabits,
      usesAlcohol,
      usesTobacco,
      usesDrugs;

  ReportModel({
    this.id,
    this.familyHistory,
    this.specifyFamilyHistory,
    this.specifyPersonalHistory,
    this.previousDiabetes,
    this.diabetesComplications,
    this.previousHTN,
    this.specifyAllergy,
    this.allergyTreatment,
    this.specifySurgery,
    this.menarche,
    this.ageFirstIntercourse,
    this.numberOfIVGs,
    this.breastfeeding,
    this.numberOfPregnancies,
    this.numberOfParity,
    this.numberOfChildren,
    this.numberOfMiscarriages,
    this.firstPregnancyAge,
    this.specifyPregnancy,
    this.contraception,
    this.hormonalContraception,
    this.gynecologicalActivity,
    this.menopause,
    this.packYear,
    this.specifyDrugUse,
    this.otherHabits,
    this.history,
    this.initialDiagnosis,
    this.total,
    this.doctorName,
    this.doctorSpecialty,
    this.patientId,
    this.noFamilyHistory,
    this.personalCancerHistory,
    this.noMedicalHistory,
    this.hasDiabetes,
    this.hasHTN,
    this.hasCoronaryDisease,
    this.hasCardiacDisease,
    this.hasRenalDisease,
    this.hasLiverDisease,
    this.hasChronicRespiratoryDisease,
    this.hasAllergy,
    this.noSurgicalHistory,
    this.hasSurgery,
    this.noObstetricGynecHistory,
    this.isPregnant,
    this.noHabits,
    this.usesAlcohol,
    this.usesTobacco,
    this.usesDrugs,
  });
}

List<ReportModel> reportList = [
  ReportModel(
    id: "1",
    familyHistory: "None",
    specifyFamilyHistory: "",
    specifyPersonalHistory: "Asthma",
    previousDiabetes: "false",
    diabetesComplications: "",
    previousHTN: "false",
    specifyAllergy: "Peanuts",
    allergyTreatment: "EpiPen",
    specifySurgery: "Appendectomy",
    menarche: "",
    ageFirstIntercourse: "",
    numberOfIVGs: "",
    breastfeeding: "",
    numberOfPregnancies: "",
    numberOfParity: "",
    numberOfChildren: "",
    numberOfMiscarriages: "",
    firstPregnancyAge: "",
    specifyPregnancy: "",
    contraception: "",
    hormonalContraception: "",
    gynecologicalActivity: "",
    menopause: "",
    packYear: "5",
    specifyDrugUse: "None",
    otherHabits: "Exercises regularly",
    history: "Shortness of breath during exercise",
    initialDiagnosis: "Mild asthma",
    total: "ras",
    doctorName: "Dr. Smith",
    doctorSpecialty: "Pulmonologist",
    patientId: "P001",
    noFamilyHistory: true,
    personalCancerHistory: false,
    noMedicalHistory: false,
    hasDiabetes: false,
    hasHTN: false,
    hasCoronaryDisease: false,
    hasCardiacDisease: false,
    hasRenalDisease: false,
    hasLiverDisease: false,
    hasChronicRespiratoryDisease: true,
    hasAllergy: true,
    noSurgicalHistory: false,
    hasSurgery: true,
    noObstetricGynecHistory: true,
    isPregnant: false,
    noHabits: false,
    usesAlcohol: false,
    usesTobacco: true,
    usesDrugs: false,
  ),
  ReportModel(
    id: "2",
    familyHistory: "Diabetes",
    specifyFamilyHistory: "Mother has diabetes",
    specifyPersonalHistory: "",
    previousDiabetes: "false",
    diabetesComplications: "",
    previousHTN: "false",
    specifyAllergy: "",
    allergyTreatment: "",
    specifySurgery: "",
    menarche: "12",
    ageFirstIntercourse: "20",
    numberOfIVGs: "0",
    breastfeeding: "true",
    numberOfPregnancies: "2",
    numberOfParity: "2",
    numberOfChildren: "2",
    numberOfMiscarriages: "0",
    firstPregnancyAge: "25",
    specifyPregnancy: "No complications",
    contraception: "true",
    hormonalContraception: "true",
    gynecologicalActivity: "Active",
    menopause: "",
    packYear: "0",
    specifyDrugUse: "None",
    otherHabits: "Healthy diet",
    history: "Routine check-up",
    initialDiagnosis: "Normal",
    total: "ras",
    doctorName: "Dr. Johnson",
    doctorSpecialty: "Gynecologist",
    patientId: "P002",
    noFamilyHistory: false,
    personalCancerHistory: false,
    noMedicalHistory: true,
    hasDiabetes: false,
    hasHTN: false,
    hasCoronaryDisease: false,
    hasCardiacDisease: false,
    hasRenalDisease: false,
    hasLiverDisease: false,
    hasChronicRespiratoryDisease: false,
    hasAllergy: false,
    noSurgicalHistory: true,
    hasSurgery: false,
    noObstetricGynecHistory: false,
    isPregnant: false,
    noHabits: true,
    usesAlcohol: false,
    usesTobacco: false,
    usesDrugs: false,
  ),
];
